### ISSUE TITLE
Outdated(?) readme and missing checks in "checked" parsing

### ISSUE THREAD

**Issue by fuchsi-fuchs** [beached/daw_json_link#206] opened 2021-01-15 18:50 UTC
The Readme mentions a difference between checked (`from_json`) and unchecked (`from_json_unchecked`) calls https://github.com/beached/daw_json_link#using-mapped-data-types . The latter don't seem to exist (anymore?). Instead the unchecked version should probably be `daw::json::from_json<MyClass, daw::json::NoCommentSkippingPolicyUnchecked>`, right?

When playing around with this, I was very surprised to find, that the "checked" version does not in fact check whether the input is valid json at all. Unused invalid numbers (even very blatantly wrong numbers `{"a":1.0fsdf3, ...}`) and especially unterminated json is not reported if all required keys have been found before the end of the string. (A behavior I expected for the trusted / "unchecked" version, but not for the "checked" version)

Is there any way to add these checks or to have a `FullyChecked` version or something like that, that checks whether the input is valid json?

Some context: When receiving json via websockets we occasionally receive faulty json strings that consist of a valid json appended to the incomplete beginning of another one (see example below). They are very obviously invalid - but relying on daw jsons parsing we might miss these issues and treat them as valid instead.

Below code does not throw an exception:
```c++
std::string test = R"({"e":"aggTrade","E":1610729466077,"s":"BTCUSDT","a":516119850,"p":"36062.5500{"e":"aggTrade","E":1610732218225,"s":"BTCUSDT","a":516218642,"p":"35943.45000000","q":"0.08800100","f":574701726,"l":574701727,"T":1610732218224,"m":false,"M":true})";
std::cout << daw::json::from_json<int, daw::json::NoCommentSkippingPolicyChecked>(test, "a") << std::endl;
```

**Comment by beached** [comment] 2021-01-15 19:19
I'll update the readme and look into the other bug.  The intent with the default `daw::json::NoCommentSkippingPolicyChecked` is the the data that is parsed is valid(minus a couple exceptions) and should be checked.  This is a bug.

**Comment by beached** [comment] 2021-01-15 19:43
OK, so what is happening here is that the data after the "a" member is never parsed and the data just following it is a valid ending.  What is happening is that when you asked to extract only member "a", the parser will skip to that member and then parse the value at that point, in this case an int, and stop.  I added a couple extra test cases with your data and it is triggering an exception when the parsed item is invalid.

For the case of only wanting to extract a single value and not the whole object, One can use either a class with a single member or the `tuple_json_mapping` helper.  It will allow you  
```
using namespace daw::json; // not necessary, just cleaner for reading here
std::cout << std::get<0>( from_json<tuple_json_mapping<json_number<"a", int>>>( test ) ) << '\n';
```

It parses to a tuple of the result types of the mappings supplied and that is why there is a std::get<0> being used to extract the int.

In most circumstances the invalid JSON would trip the checks, but in this case because of the design of extracting single members, it only looks at that one member until it ends.

**Comment by beached** [comment] 2021-01-15 20:00
779434618d2ac2241d79356551e34bf51638b866 fixes the issues with the readme and has the extra test cases added

**Comment by fuchsi-fuchs** [comment] 2021-01-15 20:54
Hmm it feels inconsistent to throw exceptions for illegal jsons with `from_json<...>(test)` but not with `from_json<...>(test, "a")`. Isn't this what the check policies should determine? "assume it is correct and just finish as fast as possible" (unchecked) vs. "actually check that it is valid" (checked)?

I also observed invalid jsons being accepted in the single argument version of `from_json`, but maybe those are more complex. At least I was not able to reproduce them with small artifical test strings. In the example from #204 though, removing the closing `}` does not produce an error.

And thanks for checking it out this quickly again :-) I really like the project and would love to use it for more of my projects in the future, as the setting of "I already know what the json looks like, just optimize for this one layout" is actually quite common :-)

**Comment by beached** [comment] 2021-01-15 21:15
I just tested removing the trailing `}` in #204 , specifically https://github.com/beached/daw_json_link/blob/release/tests/src/test_array_of_ordered.cpp (end of line 74), and it threw an exception.  Maybe I have the wrong example?  I would like to get to the bottom of that.

The expected behaviour is that it checks while parsing and it stops parsing after the requested member is extracted, in this case it made an int parser that will skip over JSON to get to that member.  When the path isn't specified it means we are starting the parsing at the root value and stopping when it is complete.

The rational for this model is that it is not uncommon for JSON to have other data before/after it(e.g. inside an HTTP request) and the design doesn't need to carry the state of the parser outside the input positions into each parser.

**Comment by beached** [comment] 2021-01-15 21:21
Another work around might be something like pre-checking with the event based parser as it should validate until the end of the root value too.  An empty handler should do most checks.  The minify example https://github.com/beached/daw_json_link/blob/release/tests/src/daw_json_minify.cpp shows how to use it.  

This introduces a cost in time though

**Comment by fuchsi-fuchs** [comment] 2021-01-16 09:48
I tested it with precisely the code that I posted in #204 and you are right, that removing the `}` in that code is being detected. When changing the order of `"a"` and `"b"` in the json, a missing closing brace is not detected though.

Just in case here is the example as I have tested it just now, not throwing an exception:
```c++

const std::string testJson = R"({"e":"depthUpdate","E":1609884707320,"s":"BTCBUSD","U":2544556159,"u":2544556219,"b":[["34198.31000000","0.00000000"],["34196.54000000","0.00453200"],["34193.34000000","0.00000000"],["34189.89000000","0.00000000"],["34188.82000000","0.00000000"],["34185.32000000","0.00000000"],["34184.84000000","0.06350200"],["34184.83000000","0.20000000"],["34180.61000000","0.08622700"],["34180.60000000","0.00000000"],["34180.59000000","0.19200000"],["34180.02000000","0.00000000"],["34180.01000000","0.00000000"],["34176.88000000","0.00000000"],["34166.48000000","0.00000000"],["34166.47000000","0.00000000"],["34159.85000000","0.03317500"],["34159.24000000","0.09394900"],["34158.29000000","1.00000000"],["34154.86000000","0.00000000"]],"a":[["34198.19000000","0.00000000"],["34198.23000000","0.00000000"],["34198.25000000","0.00000000"],["34198.27000000","0.00000000"],["34198.30000000","0.00000000"],["34198.32000000","0.00958500"],["34198.40000000","0.01232200"],["34198.41000000","0.01000000"],["34198.87000000","0.00000000"],["34199.12000000","0.00000000"],["34199.16000000","0.00000000"],["34199.42000000","0.00000000"],["34200.25000000","0.00000000"],["34200.71000000","0.03199900"],["34201.27000000","0.03100000"],["34201.62000000","0.00000000"],["34202.58000000","0.00000000"],["34204.45000000","0.00952700"],["34207.64000000","0.00000000"],["34207.74000000","0.00000000"],["34209.77000000","0.00000000"],["34209.81000000","0.20400000"],["34225.94000000","0.20200000"],["34226.60000000","0.91050000"],["34236.08000000","0.30000000"]])";

struct Fixed8JsonConverter {
	double operator( )( std::string_view sv ) const {
		return stod(std::string(sv));
	}
	
	template<typename OutputIterator>
	constexpr OutputIterator operator()(OutputIterator _it, double _f) const {
		return daw::json::utils::copy_to_iterator(_it, std::to_string(_f));
	}
};

template<JSONNAMETYPE name>
using json_fixed8 = daw::json::json_custom<name, double, Fixed8JsonConverter, Fixed8JsonConverter>;

struct Change {
	double rate;
	double amount;
};

namespace daw::json {
	template<>
	struct json_data_contract<Change> {
		using type = json_ordered_member_list<
						json_fixed8<no_name>, 
						json_fixed8<no_name>
					>;
	};
}

class DepthUpdateJson {
public:
	int64 time; // E
	std::string pairName; // s
	int64 idTo; // u
	int64 idFrom; // U
	std::vector<Change> bid; // b
	std::vector<Change> ask; // a
};

namespace daw::json {
	template<>
	struct json_data_contract<DepthUpdateJson> {
		using type = json_member_list<
			json_number<"E", int64>,
			json_string<"s">,
			json_number<"u", int64>,
			json_number<"U", int64>,
			json_array<"b", Change>,
			json_array<"a", Change>
		>;
	};
}

int main (const int argC, char* argV[] ) {
	try {
		auto parsed = daw::json::from_json<DepthUpdateJson>(testJson);
	} catch (const daw::json::json_exception &e) {
		std::cout << "daw error: " << e.reason() << " near: '" << e.parse_location() << "'"  << std::endl;
	}
}
```

**Comment by beached** [comment] 2021-01-16 17:53
release branch should have the fix.

**Comment by fuchsi-fuchs** [comment] 2021-01-20 12:12
Hey,
I only now got around to testing the fix. For me the above code still doesn't produce an exception though. I have made sure, that after installing the latest version the changes in `class_cleanup_now` are present - that is all that was changed, right?

**Comment by beached** [comment] 2021-01-20 14:43
The code https://github.com/beached/daw_json_link/issues/206#issuecomment-761536048 with 2 changes to compile on my current system a) int64 -> std::int64_t and b) using the C++17 naming via string constants is throwing an "Unexpected end of data" json_exception for me.  The changes I noted above should not come into play at all here.

Here is the code I am working with https://github.com/beached/json_error_tmp_test

**Comment by fuchsi-fuchs** [comment] 2021-01-20 16:50
While trying to reproduce the behavior with the code you linked I got a std::terminate instead of an exception when using c++20 instead of 17 and exchanging `"a"` and `"b"` in the json string (using g++ version 10.2.1). I was not able to reproduce the missing exception though - maybe I just didn't rebuild cleanly earlier today? I'm sorry for the confusion.

**Comment by beached** [comment] 2021-01-20 16:55
No worries, I want to get to bottom of this.  I just tried on a ubuntu system running gcc 10.2.0(so really close) and with `cmake -DCMAKE_CXX_STANDARD=20` and it am getting output of `daw error: Unexpected end of data near: ''`

**Comment by fuchsi-fuchs** [comment] 2021-01-20 17:02
Did you also exchange the order of the keys "a" and "b" in the json? With the changed order I am either getting `daw error: Missing member name or end of class near: ''` (c++17) or the terminate call (c++20)

**Comment by beached** [comment] 2021-01-20 17:43
OK, the terminate, see it now.  II think it should be in cleanup, with constexpr dtor code, and probably and throwing a second exception while another is in flight.  The different error in the C++17 is because it is looking for the member in the order you specified in the member list in the trait and finds the end of the class/stream first.  

Looking into a fix.

**Comment by beached** [comment] 2021-01-21 04:05
Bug was related to an inversion of conditional logic and it allowed for an exception to be thrown while others where already in play.  This lead to the termination.  
5d6832cf06d9dff970b3c662ec94261440c3d8d6 is the fix for it.  There are a couple minor changes in that too, but it's the change to not is_constant_evaluated

**Comment by beached** [comment] 2021-01-31 20:36
Closing

**Comment by beached** [comment] 2021-02-25 18:21
Reopening.  Adding a way to check for invalid data after the parsed value.  However, this is a breaking change and will require opt-in via the parse policy.  I will write up a document on usage in the near future.

**Comment by beached** [comment] 2021-02-25 18:25
b391595f1d6c687e0485d1a9d3e7392a4af207fb implements fix

**Comment by beached** [comment] 2021-02-25 22:29
For existing policies, one should be able to do something like 
```
struct CheckEndPolicy: daw::json::NoCommentSkippingPolicyChecked {
  using daw::json::NoCommentSkippingPolicyChecked::NoCommentSkippingPolicyChecked;
  using must_verify_end_of_data_is_valid = void;
};
```

And specify that instead of the default.

**Closed as completed** 2021-04-03 22:16 UTC
Labels: bug, question
